spring.application.name=management

# ?? ??
server.port=8080

# H2 ?????? ??
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:cafedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# ?? ??? (JSON)
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Asia/Seoul

# ????(????) ???
spring.main.allow-bean-definition-overriding=true